### PR TITLE
#33tczfb: Add commit-version workflow

### PR DESCRIPTION
**Pull request by SVynnytska**

### CODE REVIEW

**Comment by sgmoratilla** [comment]
Let's test it here: https://github.com/syltek/anemone-weather-service/pull/42

**Comment by sgmoratilla** [comment]
Questions:
- Is it possible to write several properties?   That is, besides `propertyPath: 'images[0].newTag'` 
- I think we need to add here https://github.com/syltek/anemone-workflows/blob/51a88db10c1595ca37e62147c667917f76d7072c/.github/workflows/build.yml#LL34C2-L34C2 a condition to stop the actions to keep triggering after every automatic commit. I don't know what user is used to commit yet.

**Review by sgmoratilla — APPROVED** [review]
I am merging as the pipeline is not ready to work with branches, we are using @main in many places.

**Comment by SVynnytska** [comment]
@sgmoratilla yep, conditions were a bit messy 😨

**Pull request merged**
